language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
  - "pypy3"
install:
  - pip install -r requirements.txt
  - pip install codecov python-coveralls
script:
  - pytest
after_success:
  - coveralls
  - codecov    
